# Generated by Django 5.1.7 on 2025-03-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morostav_site', '0002_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
