# Generated by Django 5.1.7 on 2025-03-19 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morostav_site', '0005_genre_book_cover_image_book_genre_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='morostav_site.genre'),
        ),
    ]
