# Generated by Django 5.1.7 on 2025-03-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morostav_site', '0007_alter_book_title_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=65),
        ),
    ]
